name: Craft CMS base deployment (enhance platform)

on:
  workflow_call:
    inputs:
      run_id:
        required: true
        type: string
      run_number:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      ssh_key:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      # Pull repository into the current pipeline.
      - name: Pull repository
        uses: actions/checkout@v4

      - name: Load private SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ssh_key }}

      - name: Restart PHP
        env:
          PHP_RESTART_URL: ${{ vars.cp_php_restart_url }}
          API_KEY: ${{ secrets.cp_api_key }}
        run: |
          curl -X POST -d "" \
          --url $PHP_RESTART_URL \
          --header "Authorization: Bearer $API_KEY"

      - name: Restart NGINX
        env:
          NGINX_PURGE_URL: ${{ vars.cp_nginx_purge_url }}
          API_KEY: ${{ secrets.cp_api_key }}
        run: |
          curl -X DELETE \
          --url $NGINX_PURGE_URL \
          --header "Authorization: Bearer $API_KEY"
